config/routes.rb
MeterReadings::Application.routes.draw do
  devise_for :users

  resources :readings

  resources :meters

  root :to => "home#index"

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :meter
  
  validates :meter, :value, :presence => true
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /readings
  # GET /readings.json
  def index
    @meters = current_user.meters
    @readings = Reading.all.select{|reading| @meters.include? reading.meter}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.json
  def new
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(params[:reading])

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading.meter, notice: 'Reading was successfully created.' }
        format.json { render json: @reading, status: :created, location: @reading }
      else
        format.html { render action: "new" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.json
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to @reading.meter, notice: 'Reading was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to readings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_for @reading, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :meter_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :meter_id, Meter.all.collect{|m| [m.name, m.id]}, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                readings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<%- model_class = Reading -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/readings/index.html.erb
<%- model_class = Reading -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th><%= model_class.human_attribute_name(:meter_id) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @readings.sort {|x,y| x.created_at <=> y.created_at }.each do |reading| %>
      <tr>
        <td><%= link_to l(reading.created_at, :format => :long), reading_path(reading) %></td>
        <td><%= reading.meter.name %></td>
        <td><%= reading.value %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reading_path(reading), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reading_path(reading),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reading_path,
            :class => 'btn btn-primary' %>

app/views/readings/new.html.erb
<%- model_class = Reading -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/readings/show.html.erb
<%- model_class = Reading -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:meter_id) %>:</strong></dt>
  <dd><%= link_to @reading.meter.name, @reading.meter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @reading.value %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              readings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reading_path(@reading), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reading_path(@reading),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>