config/routes.rb
MeterReadings::Application.routes.draw do
  devise_for :users

  resources :readings

  resources :meters

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MeterReadings" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">MeterReadings</a>
          <div class="container nav-collapse">
          <% if user_signed_in? %>
            <ul class="nav">
            	<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Meters <b class="caret"></b></a>
            		<ul class="dropdown-menu-inverse">
              		<% current_user.meters.each do |meter| %>
              		<li><%= link_to meter.name, meter_path(meter)  %></li>
              		<% end %>
              		<%= drop_down_divider %>
              		<li><a href="<%= new_meter_path %>"><span class="fui-plus-16" style="margin-right: 5px"></span> New</a></li>
								</ul>
							</li>
              <li><%= link_to "New reading", new_reading_path  %></li>
            </ul>
            <% end %>
            <ul class="nav pull-right">
						<% if user_signed_in? %>
						  <li><%= link_to current_user.email, edit_user_registration_path  %></li>
						  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
						<% else %>
						  <li><%= link_to "Sign up", new_user_registration_path  %></li>
						  <li><%= link_to "Login", new_user_session_path  %></li>
						<% end %>
						</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
    	<div class="span12">
      	<div class="row-fluid">
          <%= bootstrap_flash %>
          <%= yield %>

				</div><!--/row-->
    	</div>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>